
package miniraknare;

import javax.swing.JOptionPane;

/**
 * Klass that 
 * @author victorlells
 */
public class Miniraknare_JFrame extends javax.swing.JFrame {

    //membervars
    private double total1 = 0.0;
    private double total2 = 0.0;
    private String sign = "";
    private boolean clear = false;
    private double memory = 0.0;
    
    public Miniraknare_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSquare1 = new javax.swing.JButton();
        txfOutput = new javax.swing.JTextField();
        txfMemValue = new javax.swing.JTextField();
        btnMult = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnNumber1 = new javax.swing.JButton();
        btnNumber2 = new javax.swing.JButton();
        btnNumber3 = new javax.swing.JButton();
        btnNumber4 = new javax.swing.JButton();
        btnNumber5 = new javax.swing.JButton();
        btnNumber6 = new javax.swing.JButton();
        btnNumber7 = new javax.swing.JButton();
        btnNumber8 = new javax.swing.JButton();
        btnNumber9 = new javax.swing.JButton();
        btnNumber0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnClearMemory = new javax.swing.JButton();
        btnRecallMem = new javax.swing.JButton();
        btnAddMemory = new javax.swing.JButton();
        btnSubMemory = new javax.swing.JButton();
        btnChangeValue = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnPow2 = new javax.swing.JButton();
        btnPow3 = new javax.swing.JButton();
        btnOneDiv = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        btnPowY = new javax.swing.JButton();
        btnSquare4 = new javax.swing.JButton();
        btnSquare5 = new javax.swing.JButton();

        btnSquare1.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        btnSquare1.setText("√");
        btnSquare1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSquare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquare1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 350));

        txfOutput.setEditable(false);
        txfOutput.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N

        txfMemValue.setFont(new java.awt.Font("Century Schoolbook", 0, 24)); // NOI18N
        txfMemValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfMemValue.setText("M");

        btnMult.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnMult.setText("*");
        btnMult.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSub.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnSub.setText("-");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnReset.setText("C");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnNumber1.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber1.setText("1");
        btnNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber1ActionPerformed(evt);
            }
        });

        btnNumber2.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber2.setText("2");
        btnNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber2ActionPerformed(evt);
            }
        });

        btnNumber3.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber3.setText("3");
        btnNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber3ActionPerformed(evt);
            }
        });

        btnNumber4.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber4.setText("4");
        btnNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber4ActionPerformed(evt);
            }
        });

        btnNumber5.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber5.setText("5");
        btnNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber5ActionPerformed(evt);
            }
        });

        btnNumber6.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber6.setText("6");
        btnNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber6ActionPerformed(evt);
            }
        });

        btnNumber7.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber7.setText("7");
        btnNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber7ActionPerformed(evt);
            }
        });

        btnNumber8.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber8.setText("8");
        btnNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber8ActionPerformed(evt);
            }
        });

        btnNumber9.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber9.setText("9");
        btnNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber9ActionPerformed(evt);
            }
        });

        btnNumber0.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnNumber0.setText("0");
        btnNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber0ActionPerformed(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnClearMemory.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnClearMemory.setText("MC");
        btnClearMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMemoryActionPerformed(evt);
            }
        });

        btnRecallMem.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnRecallMem.setText("MR");
        btnRecallMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecallMemActionPerformed(evt);
            }
        });

        btnAddMemory.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnAddMemory.setText("M+");
        btnAddMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMemoryActionPerformed(evt);
            }
        });

        btnSubMemory.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnSubMemory.setText("M-");
        btnSubMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMemoryActionPerformed(evt);
            }
        });

        btnChangeValue.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 30)); // NOI18N
        btnChangeValue.setText("+/-");
        btnChangeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeValueActionPerformed(evt);
            }
        });

        btnSquare.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        btnSquare.setText("√");
        btnSquare.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnPow2.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 30)); // NOI18N
        btnPow2.setText("x^2");
        btnPow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPow2ActionPerformed(evt);
            }
        });

        btnPow3.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 30)); // NOI18N
        btnPow3.setText("x^3");
        btnPow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPow3ActionPerformed(evt);
            }
        });

        btnOneDiv.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 0, 36)); // NOI18N
        btnOneDiv.setText("1/x");
        btnOneDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneDivActionPerformed(evt);
            }
        });

        btnFact.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 36)); // NOI18N
        btnFact.setText("!x");
        btnFact.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });

        btnPowY.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 32)); // NOI18N
        btnPowY.setText("x^y");
        btnPowY.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPowY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowYActionPerformed(evt);
            }
        });

        btnSquare4.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 30)); // NOI18N
        btnSquare4.setText("N/A");
        btnSquare4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnSquare5.setFont(new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 30)); // NOI18N
        btnSquare5.setText("N/A");
        btnSquare5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNumber0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPow2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPowY, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOneDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSquare4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPow3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSquare5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(txfOutput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnClearMemory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddMemory, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(btnRecallMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfMemValue))
                    .addComponent(btnSubMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(txfMemValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClearMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPow2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnSquare5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnPow3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnSubMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnOneDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnRecallMem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnSquare4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(btnPowY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metod som avrundar svaret a till b decimaler 
    private double round(double a, double b){
        a = Math.round(a * Math.pow(10, b))/ Math.pow(10, b);
        return a;
    }
    
    //Metod som skriver ut svaret a
    private void answer(double a){
        double large = Math.pow(10, 14);
        if(a < large){
            txfOutput.setText( Double.toString(a));
            total1 = 0;
            total2 = 0;
            clear = true;
        }else{
            txfOutput.setText("ERROR");
        }
    }
    
    private void catchNoNum(){
        try{
       
            total1 = 0;
            total1 = total1 + Double.parseDouble( txfOutput.getText( ) ) ;
            clear = true;
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a number before "
                    + "clicking a arithmetic sign.", "No Num",
                    JOptionPane.ERROR_MESSAGE);
        }
        return;
        
    }
    
    
    //Metod som utför uträkningar
    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed

       try{
       
            btnEqual();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a number before "
                    + "clicking the Equals to button.", "No Num",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEqualActionPerformed
    
    private void btnEqual(){
        /**Switch case som beroend på tidigare angivet "sign" 
         * utför olika uträkningar med total1 & total2
        **/
        
        switch(sign){
            case "+" : total2 = total1+Double.parseDouble(txfOutput.getText()) ;
                       break;
                       
            case "-" : total2 = total1-Double.parseDouble(txfOutput.getText());
                       break;
                       
            case "*" : total2 = total1*Double.parseDouble(txfOutput.getText());
                       break;
                       
            case "/" : 
                        if(Double.parseDouble( txfOutput.getText( )) != 0.0){
                            total2 = total1 /
                            Double.parseDouble(txfOutput.getText()) ;
                        }else{
                            JOptionPane.showMessageDialog(null,
                                    "Don't Div by 0");
                            clear = true;
                        }
                        break;
                                      
            case "sq" : 
                    if(total1 < 0){
                            
                            JOptionPane.showMessageDialog(null, "THE NUMBER WAS "
                                    + "NEGATIVE", "Neg Num",
                            JOptionPane.ERROR_MESSAGE);
                            
                        }else{
                            total2 =  Math.sqrt(total1) ;
                            break; 
                        }
                

                       
            case "P2" : total2 =  Math.pow(total1, 2) ;
                       break; 
                       
            case "P3" : total2 = Math.pow(total1, 3)  ;
                       break;
                       
            case "Div1" : total2 = 1/total1 ;
                       break;
            
                       /**Här tar och använder en for loop för att kunna 
                        * multiplicera alla tidigare tal med varandra **/
            case "Fa" : 
                
                        if(total1 < 0 || (total1 % 1) != 0 ){
                            
                            JOptionPane.showMessageDialog(null, "THE NUMBER WAS "
                                    + "NEGATIVE OR A DECIMAL", "No Num",
                            JOptionPane.ERROR_MESSAGE);
                            
                        }else{
                            total2 = 1;
                            for (int i = 1; i <= Math.round(total1) ; i++ ){
                                total2 = total2 * i;
                            } 
                           break;
                        }
                        
            
            case "PowY" : total2 = Math.pow(total1, 
                    Double.parseDouble(txfOutput.getText()));
                       break;
                       
            default: total2 = Double.parseDouble(txfOutput.getText());
        }
        
        //Anropar dessa metoder
        total2 = round(total2, 3);
        answer(total2);
    }
    
    
    /**
     * Metoden skriver ut deras nummer i txfOutput om de blir anropade
     * @param evt 
     */
    private void btnNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber1ActionPerformed

        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        
        String btnOneText = txfOutput.getText() + btnNumber1.getText();
        txfOutput.setText(btnOneText);
    }//GEN-LAST:event_btnNumber1ActionPerformed
    
    private void btnNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber2ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnTwoText = txfOutput.getText() + btnNumber2.getText( );
        txfOutput.setText(btnTwoText);
    }//GEN-LAST:event_btnNumber2ActionPerformed

    private void btnNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber3ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnThreeText = txfOutput.getText() + btnNumber3.getText( );
        txfOutput.setText(btnThreeText);
    }//GEN-LAST:event_btnNumber3ActionPerformed

    private void btnNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber4ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnFourText = txfOutput.getText() + btnNumber4.getText( );
        txfOutput.setText(btnFourText);
    }//GEN-LAST:event_btnNumber4ActionPerformed

    private void btnNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber5ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnFiveText = txfOutput.getText() + btnNumber5.getText( );
        txfOutput.setText(btnFiveText);
    }//GEN-LAST:event_btnNumber5ActionPerformed

    private void btnNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber6ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnSixText = txfOutput.getText() + btnNumber6.getText( );
        txfOutput.setText(btnSixText);
    }//GEN-LAST:event_btnNumber6ActionPerformed

    private void btnNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber7ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnSevenText = txfOutput.getText() + btnNumber7.getText( );
        txfOutput.setText(btnSevenText);
    }//GEN-LAST:event_btnNumber7ActionPerformed

    private void btnNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber8ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnEightText = txfOutput.getText() + btnNumber8.getText( );
        txfOutput.setText(btnEightText);
    }//GEN-LAST:event_btnNumber8ActionPerformed

    private void btnNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber9ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnNineText = txfOutput.getText() + btnNumber9.getText( );
        txfOutput.setText(btnNineText);
    }//GEN-LAST:event_btnNumber9ActionPerformed

    private void btnNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber0ActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnZeroText = txfOutput.getText() + btnNumber0.getText( );
        txfOutput.setText(btnZeroText);
    }//GEN-LAST:event_btnNumber0ActionPerformed

    
    
    /**
     * Metoderna här under anger vilket tecken som ska 
     * användas av "btnEqualActionPerformed"
     * @param evt 
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        catchNoNum();
        sign = "+" ;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        catchNoNum();
        sign = "-" ;
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        catchNoNum();
        sign = "*" ;
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        catchNoNum();
        sign = "/" ;
    }//GEN-LAST:event_btnDivActionPerformed

    
    //Metod som rensar alla vaiabler och Output fönstret (ej minne)
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        total1 = 0.0;
        total2 = 0.0;
        sign = "";
        txfOutput.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed
    
    
    //Metod som lägger till en punkt i output fönstret ifall den blir anropad
    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        if(clear == true){
        txfOutput.setText("");
        clear = false;
        }
        String btnDotText = txfOutput.getText() + btnDot.getText( );
        txfOutput.setText(btnDotText);
    }//GEN-LAST:event_btnDotActionPerformed

    
    // Rensar memory variablen & "txfMemValue"
    private void btnClearMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMemoryActionPerformed
        memory = 0;
        txfMemValue.setText(Double.toString(memory));
    }//GEN-LAST:event_btnClearMemoryActionPerformed
    
    // Sätter värdet hos memory variablen i txfOutput
    private void btnRecallMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecallMemActionPerformed

        txfOutput.setText(Double.toString(memory));
        txfMemValue.setText(Double.toString(memory));
        clear = true;
    }//GEN-LAST:event_btnRecallMemActionPerformed
    
    // Adderar txfOutput värdet till memory variablen &  updaterar "txfMemValue"
    private void btnAddMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMemoryActionPerformed
    try{
       
        memory = memory + Double.parseDouble(txfOutput.getText());
        txfMemValue.setText(Double.toString(memory));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a number before "
                    + "clicking a arithmetic sign.", "No Num",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMemoryActionPerformed
    
    
    /**
     * Subtraherar txfOutput värdet till memory variablen 
     * &  updaterar "txfMemValue"
     * @param evt 
     */
    private void btnSubMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMemoryActionPerformed
    try{
       
        memory = memory - Double.parseDouble(txfOutput.getText());
        txfMemValue.setText(Double.toString(memory));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a number before "
                    + "clicking a arithmetic sign.", "No Num",
                    JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btnSubMemoryActionPerformed

    
    /**
     * Multiplicerar txfOutput värdet med -1 för att ändra teckenvärdet
     * @param evt 
     */
    private void btnChangeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeValueActionPerformed
        
        try{
       
            double a = Double.parseDouble(txfOutput.getText()) * -1;
        txfOutput.setText(Double.toString(a));
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter a number before "
                    + "reversing the value", "No Num",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnChangeValueActionPerformed
    
    
    /**
     * Metoderna här under anger vilket tecken som ska användas 
     * av "btnEqualActionPerformed"
     * @param evt 
     */
    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        catchNoNum();
        sign = "sq" ;
        btnEqual();
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnPow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPow2ActionPerformed
        catchNoNum();
        sign = "P2" ;
        btnEqual();
    }//GEN-LAST:event_btnPow2ActionPerformed

    private void btnPow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPow3ActionPerformed
        catchNoNum();
        sign = "P3" ;
        btnEqual();
    }//GEN-LAST:event_btnPow3ActionPerformed

    private void btnOneDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneDivActionPerformed
        catchNoNum();
        sign = "Div1" ;
        btnEqual();
    }//GEN-LAST:event_btnOneDivActionPerformed

    private void btnSquare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquare1ActionPerformed
    }//GEN-LAST:event_btnSquare1ActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        catchNoNum();
        sign = "Fa" ;
        btnEqual();
    }//GEN-LAST:event_btnFactActionPerformed

    private void btnPowYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowYActionPerformed
        catchNoNum();
        sign = "PowY" ;
    }//GEN-LAST:event_btnPowYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Miniraknare_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Miniraknare_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddMemory;
    private javax.swing.JButton btnChangeValue;
    private javax.swing.JButton btnClearMemory;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnNumber0;
    private javax.swing.JButton btnNumber1;
    private javax.swing.JButton btnNumber2;
    private javax.swing.JButton btnNumber3;
    private javax.swing.JButton btnNumber4;
    private javax.swing.JButton btnNumber5;
    private javax.swing.JButton btnNumber6;
    private javax.swing.JButton btnNumber7;
    private javax.swing.JButton btnNumber8;
    private javax.swing.JButton btnNumber9;
    private javax.swing.JButton btnOneDiv;
    private javax.swing.JButton btnPow2;
    private javax.swing.JButton btnPow3;
    private javax.swing.JButton btnPowY;
    private javax.swing.JButton btnRecallMem;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSquare1;
    private javax.swing.JButton btnSquare4;
    private javax.swing.JButton btnSquare5;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnSubMemory;
    private javax.swing.JTextField txfMemValue;
    private javax.swing.JTextField txfOutput;
    // End of variables declaration//GEN-END:variables
}
